version: 1

auto_review:
  enabled: true
  drafts: true 
  request_changes_workflow: auto
  request_review_on_new_commits: true
  max_total_comments: 30
  max_review_duration_minutes: 15
  path_filters:
    include:
      - "admin/**"
      - "web/**"
      - "packages/**"
      - "supabase/**"
      - "docs/**"
    exclude:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.lock"
      - "**/pnpm-lock.yaml"
      - "**/yarn.lock"
      - "**/package-lock.json"
      - "**/dist/**"
      - "**/.next/**"
      - "**/coverage/**"
      - "**/*.snap"
  ignore_labels:
    - "skip-ai-review"
    - "no-bots"
    - "dependencies"
  ignore_authors:
    - "dependabot"
    - "renovate"
  languages:
    - typescript
    - javascript
    - sql
  summary:
    enabled: true
    mode: always

qa_assistant:
  enabled: false

labeler:
  enabled: false

